// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.19.6
// source: backtrace_data.proto

package backtrace_data

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Generalised message containing information regarding a single stacktrace
// item.
type BacktraceData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	FilePath     string `protobuf:"bytes,2,opt,name=filePath,proto3" json:"filePath,omitempty"`
	LineNumber   uint32 `protobuf:"varint,3,opt,name=lineNumber,proto3" json:"lineNumber,omitempty"`
	ColumnNumber uint32 `protobuf:"varint,4,opt,name=columnNumber,proto3" json:"columnNumber,omitempty"`
	Code         string `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *BacktraceData) Reset() {
	*x = BacktraceData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backtrace_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BacktraceData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BacktraceData) ProtoMessage() {}

func (x *BacktraceData) ProtoReflect() protoreflect.Message {
	mi := &file_backtrace_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BacktraceData.ProtoReflect.Descriptor instead.
func (*BacktraceData) Descriptor() ([]byte, []int) {
	return file_backtrace_data_proto_rawDescGZIP(), []int{0}
}

func (x *BacktraceData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BacktraceData) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *BacktraceData) GetLineNumber() uint32 {
	if x != nil {
		return x.LineNumber
	}
	return 0
}

func (x *BacktraceData) GetColumnNumber() uint32 {
	if x != nil {
		return x.ColumnNumber
	}
	return 0
}

func (x *BacktraceData) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

var File_backtrace_data_proto protoreflect.FileDescriptor

var file_backtrace_data_proto_rawDesc = []byte{
	0x0a, 0x14, 0x62, 0x61, 0x63, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x64, 0x61, 0x74, 0x61,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x1c, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x74, 0x72, 0x6c,
	0x2e, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x62, 0x61, 0x63, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x97, 0x01, 0x0a, 0x0d, 0x42, 0x61, 0x63, 0x6b, 0x74, 0x72, 0x61,
	0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x69,
	0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x12, 0x1e, 0x0a, 0x0a, 0x6c, 0x69, 0x6e, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x6c, 0x69, 0x6e, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x22, 0x0a, 0x0c, 0x63, 0x6f, 0x6c, 0x75, 0x6d, 0x6e,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x6f,
	0x6c, 0x75, 0x6d, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x42, 0x41,
	0x5a, 0x3f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x75, 0x74,
	0x68, 0x65, 0x6e, 0x74, 0x75, 0x72, 0x61, 0x2f, 0x63, 0x6f, 0x64, 0x65, 0x63, 0x74, 0x72, 0x6c,
	0x2d, 0x67, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x73, 0x2f, 0x64, 0x61,
	0x74, 0x61, 0x2f, 0x62, 0x61, 0x63, 0x6b, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_backtrace_data_proto_rawDescOnce sync.Once
	file_backtrace_data_proto_rawDescData = file_backtrace_data_proto_rawDesc
)

func file_backtrace_data_proto_rawDescGZIP() []byte {
	file_backtrace_data_proto_rawDescOnce.Do(func() {
		file_backtrace_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_backtrace_data_proto_rawDescData)
	})
	return file_backtrace_data_proto_rawDescData
}

var file_backtrace_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_backtrace_data_proto_goTypes = []interface{}{
	(*BacktraceData)(nil), // 0: codectrl.data.backtrace_data.BacktraceData
}
var file_backtrace_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_backtrace_data_proto_init() }
func file_backtrace_data_proto_init() {
	if File_backtrace_data_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_backtrace_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BacktraceData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backtrace_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_backtrace_data_proto_goTypes,
		DependencyIndexes: file_backtrace_data_proto_depIdxs,
		MessageInfos:      file_backtrace_data_proto_msgTypes,
	}.Build()
	File_backtrace_data_proto = out.File
	file_backtrace_data_proto_rawDesc = nil
	file_backtrace_data_proto_goTypes = nil
	file_backtrace_data_proto_depIdxs = nil
}
